apiUmbrella:
  mongodb: "mongodb://10.0.10.159:27017,10.0.11.105:27017/api_umbrella_staging"
  elasticsearch:
    hosts:
      - host: 10.0.10.159
        port: 9200
      - host: 10.0.11.105
        port: 9200
  proxy:
    workers: 4
  router_global_rate_limits:
    ip_rate: "10000r/s"
    ip_burst: 10000
    ip_connections: 10000
