apiUmbrella:
  mongodb: "mongodb://ip-10-112-65-20.ec2.internal:27017,ip-10-28-250-152.ec2.internal:27017/api_umbrella_production"
  elasticsearch:
    hosts:
      - host: "ip-10-112-65-20.ec2.internal"
        port: 9200
      - host: "ip-10-28-250-152.ec2.internal"
        port: 9200
  proxy:
    workers: 4
